version: '3.8'

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.dev.db
    ports:
      - "5432:5432"
    networks:
      - default
  web:
    build:
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/web_django
    env_file:
      - .env.dev
    ports:
      - '8000:8000'
    depends_on:
      - db
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  postgres_data: