# Generated by Django 5.0.3 on 2024-03-29 09:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0003_alter_user_options_user_date_joined_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
